Repository Last-Survivors-3-8/Watcher-Habit-Client, pull requests merged in 2023-09, with the labels that each got.

#1 Setting tailwind 설정 및 PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package-lock.json
  package.json
  src/tailwind.css
  tailwind.config.js
Labels: enhancement

#6 Feature 습관 생성 및 수정 컴포넌트
  src/hooks/useFetchUserInfo.js
  src/hooks/useGroups.js
  src/hooks/useHandleSubmit.js
  src/hooks/useValidationForm.js
  src/lib/createHabit/createHabitData.js
  src/pages/CreateHabit/forms/DateForm.js
  src/pages/CreateHabit/forms/GroupForm.js
  src/pages/CreateHabit/forms/HabitInfoForm.js
  src/pages/CreateHabit/forms/MinApprovalForm.js
  src/pages/CreateHabit/forms/PenaltyForm.js
  src/pages/CreateHabit/forms/RepeatForm.js
  src/pages/CreateHabit/forms/TimeForm.js
  src/pages/CreateHabit/forms/ValidationForm.js
  src/pages/CreateHabit/index.js
  src/pages/CreateHabit/utils/CancelButton.js
  src/pages/CreateHabit/utils/SubmitButton.js
  src/pages/CreateHabit/utils/Tooltip.js
  src/utils/formatDate.js
  src/utils/timeUtils.js
Labels: enhancement

#8 Feature 목록 컴포넌트
  package-lock.json
  src/App.js
  src/components/habits/GroupInviteButton.js
  src/components/habits/HabitCreateButton.js
  src/components/habits/HabitDetail.js
  src/components/habits/HabitItem.js
  src/components/habits/HabitList.js
  src/hooks/useDailyHabits.js
  src/pages/CreateHabit/index.js
  src/pages/Group/index.js
  src/pages/MyHabit/index.js
  src/redux/habitSlice.js
  src/redux/store.js
  src/tailwind.css
  src/utils/getCurrentDate.js
Labels: enhancement

#10 Feature 상세 컴포넌트
  package-lock.json
  src/components/common/Header.js
  src/components/habits/HabitDetail.js
  src/components/habits/HabitDetail/AuthorAndVisibility.js
  src/components/habits/HabitDetail/ClockArcs.js
  src/components/habits/HabitDetail/EmptyHabitDetailState.js
  src/components/habits/HabitDetail/ErrorMessage.js
  src/components/habits/HabitDetail/HabitDaysOfWeek.js
  src/components/habits/HabitDetail/HabitDetail.js
  src/components/habits/HabitDetail/HabitDuration.js
  src/components/habits/HabitDetail/HabitSection.js
  src/components/habits/HabitDetail/HabitTime.js
  src/components/habits/HabitDetail/WatcherActions.js
  src/components/habits/HabitDetail/WatcherButton.js
  src/components/habits/HabitDetail/WatcherList.js
  src/components/habits/HabitItem.js
  src/components/habits/HabitList.js
  src/pages/CreateHabit/forms/GroupForm.js
  src/pages/CreateHabit/index.js
  src/pages/Group/index.js
  src/pages/MyHabit/index.js
  src/redux/habitSlice.js
  src/services/api/watcher.js
  src/tailwind.css
  src/utils/objectUtils.js
  tailwind.config.js
Labels: enhancement

#12 Feature: 그룹 생성 모달
  src/components/Sidebar/CreateGroupButton.js
  src/components/Sidebar/Sidebar.js
  src/components/modals/CreateGroup.js
Labels: enhancement

#11 Feature 인증 컴포넌트
  src/App.js
  src/components/habits/HabitDetail/AuthorAndVisibility.js
  src/components/habits/HabitDetail/EmptyHabitDetailState.js
  src/components/habits/HabitDetail/HabitDetail.js
  src/components/habits/HabitDetailAndVerification.js
  src/components/habits/Tabs.js
  src/components/habits/TitleAndAuthorInfo.js
  src/components/habits/habitList/GroupInviteButton.js
  src/components/habits/habitList/HabitCreateButton.js
  src/components/habits/habitList/HabitItem.js
  src/components/habits/habitList/HabitList.js
  src/components/habits/verification/ApprovalBox.js
  src/components/habits/verification/AwaitingVerification.js
  src/components/habits/verification/CountdownTimer.js
  src/components/habits/verification/HabitVerification.js
  src/components/habits/verification/SuccessCriteria.js
  src/components/habits/verification/SuccessOrFailure.js
  src/components/habits/verification/UploadImage.js
  src/components/habits/verification/VerificationImage.js
  src/components/habits/verification/WaitingVerification.js
  src/components/habits/verification/approvalsList/ApprovalButtons.js
  src/components/habits/verification/approvalsList/ApprovalItem.js
  src/components/habits/verification/approvalsList/ApprovalsList.js
  src/components/habits/verification/icon/Approved.js
  src/components/habits/verification/icon/CannotVerifyYet.js
  src/components/habits/verification/icon/Failure.js
  src/components/habits/verification/icon/ImageIcon.js
  src/components/habits/verification/icon/PreVerification.js
  src/components/habits/verification/icon/Rejected.js
  src/components/habits/verification/icon/Verification.js
  src/components/habits/verification/lib/UnderlinedText.js
  src/components/sidebar/CreateGroupButton.js
  src/components/sidebar/GroupItem.js
  src/components/sidebar/GroupList.js
  src/components/sidebar/HamburgerButton.js
  src/components/sidebar/JoinedGroupsButton.js
  src/components/sidebar/MyHabitPageButton.js
  src/components/sidebar/Sidebar.js
  src/components/sidebar/icon/ArrowDown.js
  src/components/sidebar/icon/ArrowUp.js
  src/components/sidebar/icon/CreateGroup.js
  src/components/sidebar/icon/JoinedGroups.js
  src/components/sidebar/icon/LeftHamburger.js
  src/components/sidebar/icon/MyHabit.js
  src/components/sidebar/icon/RightHamburger.js
  src/lib/isLoginUser.js
  src/pages/Group/index.js
  src/pages/MyHabit/index.js
  src/services/api/habitGet.js
  src/tailwind.css
  tailwind.config.js
Labels: enhancement

#14 Feature 그룹 초대 모달
  src/components/habits/habitList/GroupInviteButton.js
  src/components/habits/habitList/HabitList.js
  src/components/modals/CreateGroup.js
  src/components/modals/InviteGroup.js
  src/components/sidebar/Sidebar.js
Labels: enhancement

#15 Feature 주간 습관 목록 모달
  src/components/modals/weeklySchedule/WeeklyHabitList.js
  src/components/modals/weeklySchedule/WeeklySchedule.js
  src/components/modals/weeklySchedule/WeeklyScheduleModal.js
  src/components/modals/weeklySchedule/icon/DoubleCircle.js
  src/components/modals/weeklySchedule/icon/SquareArrowLeft.js
  src/components/modals/weeklySchedule/icon/SquareArrowRight.js
  src/components/sidebar/Sidebar.js
  src/components/sidebar/WeeklyScheduleButton.js
  src/components/sidebar/icon/WeeklyHabitsList.js
  src/constants/constants
  src/constants/daysConstants.js
  src/hooks/useWeeklySchedule.js
  src/lib/loading/Loading.js
  src/utils/dateUtils.js
  src/utils/getStartAndEndOfWeek.js
Labels: enhancement

#18 Refactor 클라이언트 리팩토링 1차
  src/components/common/Profile.js
  src/components/habits/HabitDetail/HabitDetail.js
  src/components/habits/HabitDetail/HabitDuration.js
  src/components/habits/HabitDetail/HabitTime.js
  src/components/habits/HabitDetail/WatcherActions.js
  src/components/habits/HabitDetail/icon/Watcher.js
  src/components/habits/HabitDetailAndVerification.js
  src/components/habits/Tabs.js
  src/components/habits/habitList/HabitItem.js
  src/components/habits/habitList/HabitList.js
  src/components/modals/CreateGroup.js
  src/components/notifications/NotificationItem.js
  src/components/notifications/NotificationList.js
  src/hooks/useValidationForm.js
  src/pages/CreateHabit/forms/DateForm.js
  src/pages/CreateHabit/forms/GroupForm.js
  src/pages/CreateHabit/forms/HabitInfoForm.js
  src/pages/CreateHabit/forms/MinApprovalForm.js
  src/pages/CreateHabit/forms/PenaltyForm.js
  src/pages/CreateHabit/forms/RepeatForm.js
  src/pages/CreateHabit/forms/TimeForm.js
  src/pages/CreateHabit/forms/ValidationForm.js
  src/pages/CreateHabit/forms/message/validationMessages.js
  src/pages/CreateHabit/index.js
  src/pages/CreateHabit/utils/CancelButton.js
  src/pages/CreateHabit/utils/SubmitButton.js
  src/tailwind.css
Labels: refactor

#19 Feature 배치 알림 관련
  src/components/common/Profile.js
  src/components/realTimeNotifications/ActionButton.js
  src/components/realTimeNotifications/CloseButton.js
  src/components/realTimeNotifications/NotificationContent.js
  src/components/realTimeNotifications/NotificationMessage.js
  src/components/realTimeNotifications/RealTimeNotifications.js
  src/utils/initEventSource.js
Labels: enhancement

#17 Feature 기존 주간 습관 목록에 히스토리 기능 추가
  public/images/carousel/image1.png
  public/images/carousel/image2.png
  public/images/carousel/image3.png
  public/images/carousel/image4.png
  public/images/carousel/image5.png
  src/components/modals/weeklySchedule/HabitImageModal.js
  src/components/modals/weeklySchedule/WeeklyHabitList.js
  src/components/modals/weeklySchedule/WeeklySchedule.js
  src/components/modals/weeklySchedule/utils/getStatusBorderColor.js
  src/components/modals/weeklySchedule/utils/getStatusMessage.js
  src/hooks/useWeeklySchedule.js
Labels: enhancement

#20 Refactor 클라이언트 리팩토링 2차
  src/App.js
  src/components/habits/HabitDetail/HabitDetail.js
  src/components/habits/Tabs.js
  src/components/habits/habitList/HabitCreateButton.js
  src/components/habits/habitList/HabitItem.js
  src/components/habits/habitList/HabitList.js
  src/components/modals/CreateGroup.js
  src/components/sidebar/CreateGroupButton.js
  src/components/sidebar/WeeklyScheduleButton.js
  src/hooks/useHandleSubmit.js
  src/pages/Group/index.js
  src/pages/MyHabit/index.js
Labels: refactor

#21 Fix 초기 접속시 오류 해결
  public/index.html
  src/App.js
  src/components/common/GoogleLoginButton.js
  src/hooks/useDocumentTitle.js
  src/lib/login/loginAndRedirect.js
  src/pages/CreateHabit/index.js
  src/pages/CreateNickname/index.js
  src/pages/Group/index.js
  src/pages/Home/index.js
  src/pages/MyHabit/index.js
  src/pages/NotFound/index.js
  src/pages/ServerError/index.js
Labels: bug, refactor

#22 Refactor 리팩토링 작업
  src/components/habits/habitList/GroupInviteButton.js
  src/components/habits/habitList/icon/GroupInvite.js
  src/components/modals/InviteGroup.js
  src/components/notifications/NotificationList.js
  src/components/notifications/icon/Logout.js
  src/components/sidebar/CreateGroupButton.js
  src/components/sidebar/GroupItem.js
  src/components/sidebar/GroupList.js
  src/components/sidebar/HamburgerButton.js
  src/components/sidebar/JoinedGroupsButton.js
  src/components/sidebar/MyHabitPageButton.js
  src/components/sidebar/Sidebar.js
  src/components/sidebar/WeeklyScheduleButton.js
  src/components/sidebar/icon/CreateGroup.js
  src/components/sidebar/icon/LeftHamburger.js
  src/components/sidebar/icon/MyHabit.js
  src/components/sidebar/icon/RightHamburger.js
  src/pages/CreateHabit/index.js
  src/pages/Group/index.js
Labels: refactor
