Repository Last-Survivors-3-8/Watcher-Habit-Client, pull requests merged in 2023-10, with the labels that each got.

#23 Refactor & Fix: 클라이언트 리팩토링 3차 및 버그 픽스 (+ README.md 초안 작성)
  README.md
  package-lock.json
  package.json
  src/App.js
  src/components/common/GoogleLoginButton.js
  src/components/common/Profile.js
  src/components/common/bellIcon.js
  src/components/habits/HabitDetail/HabitDetail.js
  src/components/habits/HabitDetail/HabitDuration.js
  src/components/habits/HabitDetail/HabitTime.js
  src/components/habits/HabitDetail/WatcherActions.js
  src/components/habits/HabitDetailAndVerification.js
  src/components/habits/TitleAndAuthorInfo.js
  src/components/habits/habitList/GroupInviteButton.js
  src/components/habits/verification/HabitVerification.js
  src/components/habits/verification/VerificationImage.js
  src/components/habits/verification/approvalsList/ApprovalItem.js
  src/components/modals/CreateGroup.js
  src/components/modals/InviteGroup.js
  src/components/modals/weeklySchedule/WeeklyHabitList.js
  src/components/modals/weeklySchedule/WeeklySchedule.js
  src/components/modals/weeklySchedule/icon/DoubleCircle.js
  src/components/modals/weeklySchedule/utils/formatDate.js
  src/components/realTimeNotifications/RealTimeNotifications.js
  src/components/sidebar/CreateGroupButton.js
  src/components/sidebar/GroupList.js
  src/components/sidebar/JoinedGroupsButton.js
  src/components/sidebar/Sidebar.js
  src/hooks/useDailyHabits.js
  src/hooks/useFetchUserData.js
  src/lib/login/loginAndRedirect.js
  src/pages/AwsS3Test/index.js
  src/pages/CreateHabit/forms/GroupForm.js
  src/pages/CreateHabit/forms/MinApprovalForm.js
  src/pages/CreateHabit/forms/PenaltyForm.js
  src/pages/CreateHabit/forms/TimeForm.js
  src/pages/CreateHabit/index.js
  src/pages/CreateHabit/utils/SubmitButton.js
  src/pages/CreateNickname/index.js
  src/pages/Group/index.js
  src/pages/Home/index.js
  src/pages/MyHabit/index.js
  src/pages/NotFound/index.js
  src/services/api/groupGet.js
  src/utils/api.js
  tailwind.config.js
Labels: bug, enhancement, refactor

#24 Feature 토큰 재발급 관련 작업
  src/components/common/Profile.js
  src/components/habits/HabitDetail/HabitDetail.js
  src/components/habits/habitList/HabitItem.js
  src/components/habits/verification/UploadImage.js
  src/components/habits/verification/approvalsList/ApprovalItem.js
  src/components/modals/CreateGroup.js
  src/components/modals/InviteGroup.js
  src/components/notifications/NotificationItem.js
  src/components/realTimeNotifications/RealTimeNotifications.js
  src/constants/errorMessages.js
  src/hooks/useDailyHabits.js
  src/hooks/useGroups.js
  src/hooks/useHandleSubmit.js
  src/hooks/useWeeklySchedule.js
  src/lib/api.js
  src/lib/login/loginAndRedirect.js
  src/services/api/groupGet.js
  src/services/api/habitGet.js
  src/services/api/login.js
  src/services/api/logout.js
  src/services/api/notificationListGet.js
  src/services/api/userCheck.js
  src/services/api/userGet.js
  src/services/api/userPost.js
  src/services/api/watcher.js
  src/utils/api.js
Labels: enhancement

#25 Feature README.md 작성
  README.md
  public/images/carousel/image1.png
  public/images/carousel/image2.png
  public/images/carousel/image3.png
  public/images/carousel/image4.png
  public/images/carousel/image5.png
Labels: enhancement

#27 Refactor 전체 모듈 가독성 및 일관성을 위한 수정
  README.md
  src/components/common/GoogleLoginButton.js
  src/components/common/Logo.js
  src/components/common/LogoutButton.js
  src/components/common/Profile.js
  src/components/habits/HabitDetail/WatcherActions.js
  src/components/modals/CreateGroup.js
  src/components/modals/InviteGroup.js
  src/components/modals/VerifyHabit.js
  src/components/modals/weeklySchedule/HabitImageModal.js
  src/components/modals/weeklySchedule/WeeklyScheduleModal.js
  src/components/notifications/NotificationList.js
  src/components/sidebar/JoinedGroupsButton.js
  src/components/sidebar/Sidebar.js
  src/hooks/useClickOutside.js
  src/hooks/useDailyHabits.js
  src/hooks/useDocumentTitle.js
  src/hooks/useFetchHabitData.js
  src/hooks/useFetchUserData.js
  src/hooks/useFetchUserInfo.js
  src/hooks/useGroups.js
  src/hooks/useHandleSubmit.js
  src/hooks/useProfileImage.js
  src/hooks/useValidationForm.js
  src/lib/createHabit/createHabitData.js
  src/lib/user/checkUserByEmail.js
  src/lib/user/getUserProfileImage.js
  src/pages/AwsS3Test/index.js
  src/pages/CreateHabit/index.js
  src/pages/CreateNickname/index.js
  src/pages/Group/index.js
  src/pages/Home/index.js
  src/pages/MyHabit/index.js
  src/pages/NotFound/index.js
  src/pages/ServerError/index.js
  src/services/api/auth/logout.js
  src/services/api/group/getGroup.js
  src/services/api/habit/getHabit.js
  src/services/api/habit/watcher/watcher.js
  src/services/api/login.js
  src/services/api/notificationListGet.js
  src/services/api/user/checkUser.js
  src/services/api/user/getUser.js
  src/services/api/user/postUser.js
  src/services/api/userGet.js
  src/services/aws/s3.js
  src/utils/timeUtils.js
Labels: refactor

#26 Refactor api 호출 분리, 정리 작업
  src/components/common/Logo.js
  src/components/common/Profile.js
  src/components/habits/HabitDetail/HabitDetail.js
  src/components/habits/habitList/HabitItem.js
  src/components/habits/verification/HabitVerification.js
  src/components/habits/verification/UploadImage.js
  src/components/habits/verification/WaitingVerification.js
  src/components/habits/verification/approvalsList/ApprovalItem.js
  src/components/modals/CreateGroup.js
  src/components/modals/InviteGroup.js
  src/components/notifications/NotificationItem.js
  src/components/notifications/NotificationList.js
  src/components/realTimeNotifications/RealTimeNotifications.js
  src/hooks/useFetchHabitData.js
  src/hooks/useFetchUserData.js
  src/hooks/useFetchUserInfo.js
  src/hooks/useGroups.js
  src/hooks/useHandleSubmit.js
  src/hooks/useProfileImage.js
  src/hooks/useWeeklySchedule.js
  src/lib/api.js
  src/lib/isLoggedinUser.js
  src/lib/login/loginAndRedirect.js
  src/pages/Group/index.js
  src/pages/MyHabit/index.js
  src/services/api/auth/logout.js
  src/services/api/auth/postRefreshToken.js
  src/services/api/getNotificationList.js
  src/services/api/group/getGroup.js
  src/services/api/group/patchGroup.js
  src/services/api/group/postGroup.js
  src/services/api/group/postInviteGroup.js
  src/services/api/habit/deleteHabit.js
  src/services/api/habit/getHabit.js
  src/services/api/habit/getPeriodicHabits.js
  src/services/api/habit/patchHabit.js
  src/services/api/habit/postHabit.js
  src/services/api/habit/postHabitImage.js
  src/services/api/habit/watcher/watcher.js
  src/services/api/login.js
  src/services/api/user/checkUser.js
  src/services/api/user/getInfoByEmail.js
  src/services/api/user/getUser.js
  src/services/api/user/postUser.js
  src/services/aws/s3.js
  src/utils/initEventSource.js
Labels: refactor
